version: '3'
services:
  mysql:
    image: mariadb:10.4
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: crud
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: crudlex-symfony4-sample
    ports:
      - 8080:80
    volumes:
      - ..:/srv/app:delegated
    links:
      - mysql
    depends_on:
      - mysql
    command: bash -c ./docker/serve.sh